TestControllers/config/routes.rb
Rails.application.routes.draw do
  post 'relationships/create'
  delete 'relationships/destroy'

  resources :users, except: %i[new edit] do
    get :following, :followers, on: :member
    post :upload, on: :member
  end

  get '/signup', to: 'registration#new'
  post '/signup', to: 'registration#sign_up'

  get '/login', to: 'authentication#new'
  post '/login', to: 'authentication#login'
  delete '/logout', to: 'authentication#logout', as: 'logout'

  root 'users#index'

  resources :folders, except: %i[new edit] do
    get :learn, on: :collection
    resources :cards, only: %i[create update destroy]
  end
end

TestControllers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

TestControllers/app/models/card.rb
class Card < ApplicationRecord
  belongs_to :folder
end

TestControllers/app/models/folder.rb
class Folder < ApplicationRecord
  has_many :cards, dependent: :destroy
  belongs_to :user

  validates :name, presence: true
end

TestControllers/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

TestControllers/app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  has_secure_password

  has_many :folders, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  has_many :passive_relatioships, class_name: 'Relationship',
                                  foreign_key: 'followed_id',
                                  dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relatioships, source: :follower

  has_one_attached :avatar

  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  # validates :password, presence: true, length: { minimum: 6 } ты не можешь валидировать пароль таким образом. Он в базе хранится зашифрованным

  def follow(another_user)
    return if active_relationships.exists?(followed_id: another_user.id)

    active_relationships.create(followed_id: another_user.id)
  end

  def unfollow(another_user)
    return unless active_relationships.exists?(followed_id: another_user.id)

    active_relationships.find_by(followed_id: another_user.id).destroy
  end

  def following?(another_user)
    following.include?(another_user)
  end
end

TestControllers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

TestControllers/app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def new
    @user = User.new
  end

  def login
    @user = User.find_by(email: params[:user][:email])

    if @user&.authenticate(params[:user][:password])
      token = encode_token(user_id: @user.id)
      set_cookie(token)

      redirect_to user_path(@user)
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new', status: :unauthorized
    end
  end

  def logout
    delete_cookie

    redirect_to root_path
  end
end

TestControllers/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def create
    @folder = Folder.find(params[:folder_id])
    @card = Card.new(card_params.merge({ folder: @folder }))

    @card.save ? flash[:success] = 'Card was created successfully' : flash[:error] = 'Card creation failed'

    redirect_to folder_cards_path(@folder)
  end

  def update
    @folder = Folder.find(params[:folder_id])
    @card = @folder.cards.find(params[:id])

    redirect_to folder_cards_path(@folder) if @card.update(card_params)
  end

  def destroy
    @folder = Folder.find(params[:folder_id])
    @card = Card.find(params[:id])

    redirect_to folder_cards_path(@folder) if @card.destroy
  end

  private

  def card_params
    params.require(:card).permit(:word, :translation)
  end
end

TestControllers/app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :find_current_user, only: %i[create update destroy]

  def index
    @folders = Folder.includes(:cards).all
  end

  def show
    @folder = Folder.find(params[:id])
  end

  def create
    @folder = Folder.new(folder_params.merge(user: @current_user))
    @folder.save

    redirect_to user_path(@current_user)
  end

  def update
    @folder = Folder.find(params[:id])

    if @folder.user.id == @current_user.id
      @folder.update(folder_params.merge(user: @current_user))
    else
      flash[:error] = "You can't change this folder"
    end

    redirect_to user_path(@current_user)
  end

  def destroy
    @folder = Folder.find(params[:id])

    if @folder.user.id == @current_user.id
      @folder.destroy
    else
      flash[:error] = "You can't delete this folder"
    end

    redirect_to user_path(@current_user)
  end

  def learn
    @cards = WordlistCreator.call
  end

  private

  def folder_params
    params.require(:folder).permit(:name)
  end

  def find_current_user
    @current_user = current_user
  end
end

TestControllers/app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
    @user = User.new
  end

  def sign_up
    @user = User.new(user_params)

    if @user.save
      token = encode_token(user_id: @user.id)
      set_cookie(token)

      UserMailer.send_signup_email(@user).deliver

      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end
end

TestControllers/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end

  def destroy
    followed_id, follower_id = params[:followed_data].split('|').map(&:to_i)

    relationship = Relationship.find_by(followed_id: followed_id, follower_id: follower_id)
    user = Relationship.find(relationship.id).followed
    current_user.unfollow(user)
    redirect_to user
  end
end

TestControllers/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: %i[show upload]

  def index
    @users = User.all
  end

  def show
    @current_user = current_user
    @folders = Folder.includes(:cards).where(user: @user)
  end

  def upload
    if params[:user].present? && params[:user][:avatar].present?
      @user.avatar.attach(params[:user][:avatar])

      redirect_to @user, notice: 'Avatar uploaded successfully!'
    else
      redirect_to @user, alert: 'No file selected for upload!'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

TestControllers/app/helpers/application_helper.rb
module ApplicationHelper
  SECRET_KEY = Rails.application.secrets.secret_key_base

  def encode_token(payload, exp = 7.days.from_now)
    payload[:exp] = exp.to_i
    JWT.encode(payload, SECRET_KEY)
  end

  def decode_token(token)
    unless token.nil?
      decoded = JWT.decode(token, SECRET_KEY)[0]
      HashWithIndifferentAccess.new decoded
    else
      return nil
    end
  end

  def current_user
    decoded = decode_token(cookies[:user_token])

    if decoded.nil?
      @current_user = nil
    else
      @current_user ||= User.find_by(id: decoded[:user_id])
    end
  end

  def logged_in?(current_user)
    !current_user.nil?
  end

  def set_cookie(token)
    cookies[:user_token] = token
  end

  def delete_cookie
    cookies.delete(:user_token)
    @current_user = nil
  end
end

TestControllers/app/helpers/cards_helper.rb
module CardsHelper
end

TestControllers/app/helpers/email_helper.rb
module EmailHelper
  def email_image_tag(image, **options)
    attachments[image] = File.read(Rails.root.join("app/assets/images/#{image}"))
    image_tag attachments[image].url, **options
  end
end

TestControllers/app/helpers/folders_helper.rb
module FoldersHelper
end

TestControllers/app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

TestControllers/app/views/authentication/new.html.erb
<% provide(:title, 'Log in') %>

<h1><%= yield(:title) %></h1>

<p>
<% unless flash.empty? %>
  <%= flash[:danger] %>
<% end %>
</p>

<%= form_with model: [@user, User.new], url: login_path, method: :post, local: true do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email, name: 'user[email]' %>

  <%= f.label :password %>
  <%= f.password_field :password, name: 'user[password]' %>

  <%= f.submit 'Log in' %>
<% end %>

<p>New user? <%= link_to 'Sign up now', signup_path %></p>

TestControllers/app/views/folders/index.html.erb
<h1>Available folders</h1>

<ol>
  <% @folders.each do |folder| %>
    <li><%= link_to folder.name, folder %></li>

    <%= form_with model: folder do |form| %>
      <%= form.text_field :name %>
      <%= form.submit 'Change' %>
    <% end %>

    <p>Number of cards: <%= folder.cards.size %></p>

    <%= button_to 'Delete', folder_path(folder), method: :delete %>
    <p></p>
  <% end %>
</ol>

<%= form_with model: @folder, url: folders_path, method: :post, local: true do |form| %>
  <%= form.text_field :name, name: 'folder[name]' %>
  <%= form.submit 'Create folder' %>
<% end %>

<%= link_to 'Learn', learn_folders_path %>

TestControllers/app/views/folders/learn.html.erb
<%= @cards %>

<% @cards.each do |hash| %> 
  <% hash.each do |word, translation| %>
    <% next if word.empty? or translation.empty? %>
    
    <p><%= word %> - <%= translation %></p>
  <% end %>
<% end %>

TestControllers/app/views/folders/show.html.erb
<h1><%= @folder.name %></h1>

<% @folder.cards.each do |card| %>
  <p><%= card.word %> - <%= card.translation %></p>

  <%= form_with model: [@folder, card], url: folder_card_path(@folder, card) do |form| %>
    <%= form.text_field :word %>
    <%= form.text_field :translation %>
    <%= form.submit 'Change' %>
  <% end %>

  <%= form_with(model: [@folder, card], url: folder_card_path(@folder, card), method: :delete) do |form| %>
    <%= form.submit 'Delete' %>
  <% end %>
<% end %>

<p></p>
<p></p>

<%= form_with model: [@folder, Card.new], url: folder_cards_path(@folder), method: :post, local: false do |form| %>
  <%= form.text_field :word,        name: 'card[word]',        placeholder: "word" %>
  <%= form.text_field :translation, name: 'card[translation]', placeholder: "translation" %>
  <%= form.submit "Create Card" %>

  <% flash.each do |type, message| %>
    <div class="flash <%= type %>"><%= message %></div>
  <% end %>
<% end %>

<p></p>
<p></p>

<%= link_to 'Back to folders', folders_path %>

TestControllers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

TestControllers/app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to "#{user.name}", user_path(user) %></li> 
  <% end %>
</ul>

TestControllers/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1><%= yield(:title) %></h1>

<%= form_with model: [@user, User.new], url: users_path, method: :post, local: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, name: 'user[name]' %>

  <%= f.label :email %>
  <%= f.email_field :email, name: 'user[email]' %>

  <%= f.label :password %>
  <%= f.password_field :password, name: 'user[password]' %>

  <%= f.label :password_confirmation, 'Confirmation' %>
  <%= f.password_field :password_confirmation, name: 'user[password_confirmation]' %>

  <%= f.submit 'Create my account' %>
<% end %>

<p><%= link_to 'Log in', login_path %></p>

TestControllers/app/views/users/show.html.erb
<% provide(:title, "#{@user.name} profile") %>

<% if logged_in?(@current_user) %>
  <%= link_to 'Profile', user_path(@current_user) %>
  <%= link_to 'Users',    users_path %>
  <%= link_to 'Settings', '#' %>
  <%= button_to 'Log out', logout_path, :method => 'delete' %>

  <% unless @user.id == @current_user.id %>
    <% if @current_user.following?(@user) %>
      <%= form_tag relationships_destroy_path, method: 'delete' do %>
        <%= hidden_field_tag :followed_data, "#{@user.id}|#{@current_user.id}" %>
        <%= submit_tag 'Unfollow' %>
      <% end %>
    <% else %>
      <%= form_tag relationships_create_path, method: 'post' do %>
        <%= hidden_field_tag :followed_id, @user.id %>
        <%= submit_tag 'Follow' %>
      <% end %>
    <% end %>
  <% end %>

  <h1>
    <%= form_with(model: @current_user, url: upload_user_path(@current_user), local: true, method: :post) do |form| %>
      <%= form.label :avatar %>
      <%= form.file_field :avatar %>
      <%= form.submit 'Upload'%>
    <% end %>

    <%= image_tag @user.avatar if @user.avatar.attached? %>

    <%= yield(:title) %>,
    <%= @user.email %>
  </h1>

  <a href="<%= following_user_path(@user) %>">following <%= @user.following.count %></a>
  <a href="<%= followers_user_path(@user) %>">followers <%= @user.followers.count %></a>

  <p>Current user's token: <%= cookies[:user_token] %></p>

  <h1>Available folders</h1>

  <ol>
    <% @folders.each do |folder| %>
      <li><%= link_to folder.name, folder %></li>

      <%= form_with model: folder do |form| %>
        <%= form.text_field :name %>
        <%= form.submit 'Change' %>
      <% end %>

      <p>Number of cards: <%= folder.cards.size %></p>

      <%= button_to 'Delete', folder_path(folder), method: :delete %>
      <p></p>
    <% end %>
  </ol>

  <%= form_with model: @folder, url: folders_path, method: :post, local: true do |form| %>
    <%= form.text_field :name, name: 'folder[name]' %>
    <%= form.submit 'Create folder' %>
  <% end %>

<% else %> 
  <%= render template: '/authentication/new' %>
<% end %>